
/**
 * OPERADORES DE CORTO CIRCUITO
 * 
 * cORTOCIRCUITO or - CUANDO EL VALOR DE LA IZQUIERDA EN LA EXPRESIÓN SIEMPRE PUEDA VALIDAR A TRUE. ES EL VALOR QUE SE CARGARÁ POR DEFECTO
 * 
 * CORTOCIRCUITO AND - CUANDO EL VALOR DE LA IZQUIERDA EN LA EXPRESIÓN SIEMPRE PUEDA VALIDAR A FALSE, ES EL VALOR QUE SE CARGARÁ POR DEFECTO
 */

